// import type { Metadata } from "next";
// import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";
// import Header from "@/components/Header";
// import Sidebar from "@/components/Sidebar";
// import { Toaster } from "@/components/ui/sonner";





// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//     <html lang="en">
//       <body>
//         <Header/>
//         <div className="flex min-h-screen">

//           <Sidebar/>
//            <div className= "flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide">
//           {children}
//         </div>
//         </div>
       
//         <Toaster position="top-center"/>
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }
import type { Metadata } from "next";
import "./globals.css";
import "./custom.css"; // Make sure to import custom styles
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "AI Notion Clone",
  description: "Real-time collaboration with Gen-Z aesthetics.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-gradient-to-br from-pink-100 via-purple-150 to-indigo-150 font-poppins transition-all duration-300">
          <Header />
          <div className="flex min-h-screen">
            <Sidebar />
            <div className="flex-1 p-4 bg-red/80 backdrop-blur-xl shadow-inner overflow-y-auto scrollbar-hide rounded-l-3xl">
              {children}
            </div>
          </div>
          <Toaster position="top-center" />
        </body>
      </html>
    </ClerkProvider>
  );
}
